#ifndef CONST_FENETRE_H_INCLUDED
#define CONST_FENETRE_H_INCLUDED

#define WIDTH 800
#define HEIGHT 600

#define WIDTH_COLONNE 200

#define HEIGHT_MIN 500 //prévision

#define Y_CAMERA 10
#define HEIGHT_CAMERA 170

#define Y_MAILLE 20+HEIGHT_CAMERA
#define HEIGHT_MAILLE 170

#define Y_VALEUR 30+HEIGHT_CAMERA+HEIGHT_MAILLE
#define HEIGHT_VALEUR 170

#endif // CONST_FENETRE_H_INCLUDED
