#ifndef CONST_FENETRE_H_INCLUDED
#define CONST_FENETRE_H_INCLUDED

#define WIDTH 1000
#define HEIGHT 640

#define WIDTH_COLONNE 300

#define HEIGHT_MIN 500 //prévision
#define WIDTH_MIN WIDTH_COLONNE+100 //prévision


#define Y_ESPACE 10

#define Y_CAMERA Y_ESPACE
#define HEIGHT_CAMERA 300

#define Y_MAILLE 2*Y_ESPACE+HEIGHT_CAMERA
#define HEIGHT_MAILLE 170

#define HEIGHT_RETRO 100

#define Y_VALEUR 3*Y_ESPACE+HEIGHT_CAMERA+HEIGHT_MAILLE
#define HEIGHT_VALEUR 170

#define ALINEA_MENU 20
#define WIDTH_MENU WIDTH_COLONNE - 2*ALINEA_MENU

#define ALINEA_BLOC 20
#define WIDTH_BLOC WIDTH_MENU-2*ALINEA_BLOC

#define Y_CHAR 15

#endif // CONST_FENETRE_H_INCLUDED
